### ISSUE TITLE
Connection refused with the right host

### ISSUE THREAD

**Issue by biablopes** [damavis/airflow-pentaho-plugin#17]
Hi folks!
I'm trying to use the pentaho library  and using CarteTransOperator. My problem is that I created the Airflow connection with all the params, but my connection is always refused with the message:
HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /kettle/executeTrans/?user=***&pass=***&rep=repo&trans=test&level=Basic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f13c76d0c50>: Failed to establish a new connection: [Errno 111] Connection refused',).
Am I doing something wrong? I'm follow the documentation.

**Comment by piffall** [comment]
Hi @biablopes 

This error usually indicates that Carte Server may not be running at [http://localhost:8081](http://localhost:8081)

Here it is how your Connection should looks like.
![image](https://user-images.githubusercontent.com/1277789/179787623-bc0170a0-571c-464d-b1f5-2af98a679cc9.png)

**Comment by biablopes** [comment]
Hi @piffall tks for your reply. 

I was using the http in the host position, but after change to the schema, I continuos with the same error.
My carte instace is running em localhost:8081 as well, if I try to run the process in the http directly it's run as well. 

This is my configuration:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/97991425/179803967-843f4ef5-a6d5-412e-955a-87854eeff201.png">

This is my carte instance:
<img width="175" alt="image" src="https://user-images.githubusercontent.com/97991425/179804103-ef6557ee-1066-4deb-bc73-06cc430919da.png">

Maybe my DAG configuration can be wrong, this is what I'm using:
trans1 = CarteTransOperator(
        pdi_conn_id='pdi_default',
        task_id="test",
        trans="test",
        dag=dag)

Tks for your help!

**Comment by piffall** [comment]
Hi again @biablopes 

That should work. Please, check if the error is the same. If it is, you have some network communication issue. Maybe you are using Docker for airflow?

Thanks.

**Comment by biablopes** [comment]
Hi @piffall,

Yes, I was trying on Docker, after your comment, I installed the Airflow locally and the error is the same. But ok, I will be continuos trying. Now that I know that my configurations is ok, maybe I find another way. Tks for your help!
