### ISSUE TITLE
airflow-pentaho-plugin installation error

### ISSUE THREAD

**Issue by pkashibh** [damavis/airflow-pentaho-plugin#2]
Hi, I'm trying to install airflow-pentaho-plugin I'm getting the following error. I'm also trying to use Python setup.py install command and the error still remains the same. Request you to help me unblock this installation process.
Environment - Python3.9
Pip version - 21.0.1
Command - sudo pip install airflow-pentaho-plugin --proxy=http://proxy:port
Error - ERROR: Could not find a version that satisfies the requirement setuptools-git-version

I've also run the requires.txt and I see the following message when I rerun:
Requirement already satisfied: xmltodict>=0.10.0 in /usr/lib/python3.9/site-packages (from -r requires.txt (line 1)) (0.12.0)

Could you please let me know what am I missing here?

Thanks,
Pavan

**Comment by piffall** [comment]
Hi @pkashibh 

Take a look at Apache Airflow requirements: https://github.com/apache/airflow#requirements , It is not tested on python3.9. I recommend you to use 3.7 or 3.8.

Thanks.
