### ISSUE TITLE
CarteTransOperator works incorrect when transformation failed

### ISSUE THREAD

**Issue by evgdol** [damavis/airflow-pentaho-plugin#30]
### Scenario (simplified)
1. We have the table in the database with constraints
`CREATE TABLE tst_constraints(
    id int PRIMARY KEY,
    val text
)`

2. We have the simple transformation that inserts the data into this table
![image](https://user-images.githubusercontent.com/126868762/227502702-104d736a-a07e-4263-88ff-002df3f57e40.png)

3. Call the transformation in Airflow
`trans = CarteTransOperator(
    task_id='tst_trans_fail',
    pdi_conn_id='pentaho',
    trans='/public/test/tr_tst_failed_tab_constraint'
)`
### Result
1. If table is empty (no constraints inconsistency) all works as expected
2. If the table contains inserted data, I have found two possible scenarios (the second is more often):
  2.1. The task finished with SUCCESS flag
![image](https://user-images.githubusercontent.com/126868762/227504659-c966f75f-d7a4-4bea-a4b9-d526760abe8b.png)
![image](https://user-images.githubusercontent.com/126868762/227504813-2662b691-d0e8-4a68-b241-27011a7cff42.png)

  2.2. The task freezing, but the transformation already failed.
![image](https://user-images.githubusercontent.com/126868762/227505035-4e213846-2b87-42e9-aec2-d83acbe59274.png)

### Expected result
CarteTransOperator works properly

### Additions
After discussion in [Issue #29 ](url):
If we wrap around the transformation in job, it works fine. But I want to know if it is possible to solve this issue without this.

#### Environment
Airflow 2.5.1 + Python 3.10 + Pentaho server CE 8.0

**Comment by evgdol** [comment]
Not solved!
![image](https://user-images.githubusercontent.com/126868762/227513055-f77a2ac6-9118-4772-8963-0c5de1a8c530.png)

**Comment by piffall** [comment]
Sorry. Now it should work.

**Comment by evgdol** [comment]
Nothing changed. The result is the same as on previous my screenshot.

**Comment by evgdol** [comment]
I have found the issue.
You should change the condition in WHILE:
![image](https://user-images.githubusercontent.com/126868762/227523119-3d69eaaa-763b-49b2-9ddd-29f308051d57.png)
There are FINISHED_STATUSES used in your code.
I have changed on my side and it works.

**Comment by piffall** [comment]
You are right @evgdol . I need to add some tests for this. But I'm about to release a version with this fix.
