### ISSUE TITLE
cannot get transformation result status Carte

### ISSUE THREAD

**Issue by 3pm** [damavis/airflow-pentaho-plugin#34]
Hello!
Pentaho 9.4 + Carte
When using CarteTransOperator it cannot get execution status:
airflow.exceptions.AirflowException: Unexpected server response: {"webresult": {"result": "ERROR", "message": "The specified transformation [trans.ktr] could not be found", "id": null}}

It's because it passes .ktr along to transformation name. If  ".ktr" is removed in _get_trans_name (carte.py file) - it works.

That's not the case in CarteJobOperator, it works.

**Comment by piffall** [comment]
Hi @nv, did you try to use just the name, without the extension? I think that the `.ktr` is not necessary.

**Comment by 3pm** [comment]
Hello.
The only place I pass path is trans='/home/xxx/pentaho/local/tmp/trans.ktr' parameter. Without full path (including .ktr) it is not working. Later the name is taken from this path in CarteTransOperator.

**Comment by 3pm** [comment]
This helps for me:
    def _get_trans_name(self):
        return self.trans.split('/').pop()**.replace(".ktr","")**

**Comment by piffall** [comment]
Fixed in v1.1.2: https://github.com/damavis/airflow-pentaho-plugin/commit/87895d1b469e0180be1e380a26d70d4c420d75f9

**Comment by 3pm** [comment]
Hello, can you put it on release 1.1.2 please?

**Comment by piffall** [comment]
That should be already there @3pm

**Comment by 3pm** [comment]
Hello, I'm sorry. Tank you. Looked at the wrong place.
