### ISSUE TITLE
Log Level Problem

### ISSUE THREAD

**Issue by Guvenntmz** [damavis/airflow-pentaho-plugin#9]
Hello,

The CarteJobOperator's "level" argument does not work sadly. As I was searching through the code, I found a bug. That is, in the Class PentahoCarteHook > PentahoCarteClient there is a hard code of "Debug" for the level parameter. Can you look into it please?

![image](https://user-images.githubusercontent.com/58135020/118603471-9bc44d00-b7bc-11eb-8dfb-4367c263bb46.png)

Thank you.

**Comment by piffall** [comment]
Hi @Guvenntmz ,

We've already released the version 1.0.8 that fixes this issue.

Thanks.
